import {Offer} from '../types/offer';

export const offers: Offer[] = [
  {
    id: 1000,
    images: ['img/apartment-01.jpg', 'img/room.jpg', 'img/apartment-03.jpg'],
    premium: true,
    price: 120,
    title: 'Beautiful &amp; luxurious apartment at great location',
    type: 'Apartment',
    isFav: false,
    rating: 4,
    rooms: 2,
    maxPers: 3,
  },
  {
    id: 1001,
    images: ['img/room.jpg'],
    premium: false,
    price: 80,
    title: 'Wood and stone place',
    type: 'Private room',
    isFav: true,
    rating: 4,
    rooms: 2,
    maxPers: 3,
  },
  {
    id: 1002,
    images: ['img/apartment-02.jpg'],
    premium: false,
    price: 132,
    title: 'Canal View Prinsengracht',
    type: 'Apartment',
    isFav: false,
    rating: 4,
    rooms: 2,
    maxPers: 3,
  },
  {
    id: 1003,
    images: ['img/apartment-03.jpg'],
    premium: true,
    price: 180,
    title: 'Nice, cozy, warm big bed apartment',
    type: 'Apartment',
    isFav: false,
    rating: 5,
    rooms: 2,
    maxPers: 3,
  },
];
